// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordVerifier is an autogenerated mock type for the PasswordVerifier type
type PasswordVerifier struct {
	mock.Mock
}

// VerifyPassword provides a mock function with given fields: password, hash
func (_m *PasswordVerifier) VerifyPassword(password string, hash string) bool {
	ret := _m.Called(password, hash)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(password, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
