// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// jwtManager is an autogenerated mock type for the jwtManager type
type jwtManager struct {
	mock.Mock
}

// VerifyToken provides a mock function with given fields: incomingtoken
func (_m *jwtManager) VerifyToken(incomingtoken string) bool {
	ret := _m.Called(incomingtoken)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(incomingtoken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
