// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// loginStateManager is an autogenerated mock type for the loginStateManager type
type loginStateManager struct {
	mock.Mock
}

// IsLogIn provides a mock function with given fields: id
func (_m *loginStateManager) IsLogIn(id string) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
