// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IventHandlerUserRepository is an autogenerated mock type for the IventHandlerUserRepository type
type IventHandlerUserRepository struct {
	mock.Mock
}

// AddMoney provides a mock function with given fields: userId, amount
func (_m *IventHandlerUserRepository) AddMoney(userId string, amount float64) error {
	ret := _m.Called(userId, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64) error); ok {
		r0 = rf(userId, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserBalance provides a mock function with given fields: userId
func (_m *IventHandlerUserRepository) GetUserBalance(userId string) (float64, error) {
	ret := _m.Called(userId)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubtractMoney provides a mock function with given fields: userId, amount
func (_m *IventHandlerUserRepository) SubtractMoney(userId string, amount float64) error {
	ret := _m.Called(userId, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64) error); ok {
		r0 = rf(userId, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
