// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReserveMoneyHandler is an autogenerated mock type for the ReserveMoneyHandler type
type ReserveMoneyHandler struct {
	mock.Mock
}

// ReserveMoney provides a mock function with given fields: userid, money, hash
func (_m *ReserveMoneyHandler) ReserveMoney(userid string, money float64, hash string) {
	_m.Called(userid, money, hash)
}

// UnReserveMoney provides a mock function with given fields: userid, money, hash
func (_m *ReserveMoneyHandler) UnReserveMoney(userid string, money float64, hash string) {
	_m.Called(userid, money, hash)
}
