// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	domain "github/namuethopro/dobet-user/domain"

	mock "github.com/stretchr/testify/mock"
)

// UserEventManager is an autogenerated mock type for the UserEventManager type
type UserEventManager struct {
	mock.Mock
}

// CreateQueues provides a mock function with given fields: _a0
func (_m *UserEventManager) CreateQueues(_a0 []string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publish provides a mock function with given fields: name, event
func (_m *UserEventManager) Publish(name string, event domain.Event) error {
	ret := _m.Called(name, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.Event) error); ok {
		r0 = rf(name, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
