// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	amqp "github.com/streadway/amqp"
	mock "github.com/stretchr/testify/mock"
)

// userEventManager is an autogenerated mock type for the userEventManager type
type userEventManager struct {
	mock.Mock
}

// CreateQueues provides a mock function with given fields: _a0
func (_m *userEventManager) CreateQueues(_a0 []string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListenningToqueue provides a mock function with given fields: queue, f
func (_m *userEventManager) ListenningToqueue(queue <-chan amqp.Delivery, f func([]byte) error) {
	_m.Called(queue, f)
}

// Publish provides a mock function with given fields: name, event
func (_m *userEventManager) Publish(name string, event interface{}) error {
	ret := _m.Called(name, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(name, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscribeToQueue provides a mock function with given fields: name
func (_m *userEventManager) SubscribeToQueue(name string) (<-chan amqp.Delivery, error) {
	ret := _m.Called(name)

	var r0 <-chan amqp.Delivery
	if rf, ok := ret.Get(0).(func(string) <-chan amqp.Delivery); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan amqp.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
