// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IncomingEventProcessorReserveMoneyManager is an autogenerated mock type for the IncomingEventProcessorReserveMoneyManager type
type IncomingEventProcessorReserveMoneyManager struct {
	mock.Mock
}

// GetReservedMoneyByUserId provides a mock function with given fields: userId
func (_m *IncomingEventProcessorReserveMoneyManager) GetReservedMoneyByUserId(userId string) float64 {
	ret := _m.Called(userId)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// ReserveMoney provides a mock function with given fields: userid, money, hash
func (_m *IncomingEventProcessorReserveMoneyManager) ReserveMoney(userid string, money float64, hash string) {
	_m.Called(userid, money, hash)
}

// UnReserveMoney provides a mock function with given fields: userid, money, hash
func (_m *IncomingEventProcessorReserveMoneyManager) UnReserveMoney(userid string, money float64, hash string) {
	_m.Called(userid, money, hash)
}
