// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Dionisio Paulo",
            "url": "meusite.com",
            "email": "dionisiopaulonamuetho@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bet": {
            "post": {
                "description": "this route allows to place your bet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "make a bet bet in the system",
                "responses": {
                    "200": {
                        "description": "bet",
                        "schema": {
                            "$ref": "#/definitions/controller.BetCreationSucessResponse"
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/controller.BetResponseError"
                        }
                    }
                }
            }
        },
        "/bets": {
            "get": {
                "description": "this route allows you to to get bets in the dobet server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get all bet in the system",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "int",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "perpage",
                        "name": "int",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "bets",
                        "schema": {
                            "$ref": "#/definitions/controller.BetListResponse"
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/controller.BetResponseError"
                        }
                    }
                }
            }
        },
        "/bets/:id": {
            "get": {
                "description": "this route allows you to bets in the dobet server by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get the bets by user id in the system",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "int",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "perpage",
                        "name": "int",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "id",
                        "name": "string",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "bets",
                        "schema": {
                            "$ref": "#/definitions/controller.BetListResponse"
                        }
                    },
                    "500": {
                        "description": "error",
                        "schema": {
                            "$ref": "#/definitions/controller.BetResponseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bet.BetBase": {
            "type": "object",
            "required": [
                "bet_owner",
                "betgroup"
            ],
            "properties": {
                "bet_id": {
                    "type": "string"
                },
                "bet_owner": {
                    "type": "string"
                },
                "betgroup": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bet.SingleBetImpl"
                    }
                },
                "is_finished": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "bet.SingleBetImpl": {
            "type": "object",
            "required": [
                "market",
                "match_id",
                "totalamount"
            ],
            "properties": {
                "is_lose": {
                    "type": "boolean"
                },
                "isprocessed": {
                    "type": "boolean"
                },
                "league_id": {
                    "type": "string"
                },
                "market": {
                    "$ref": "#/definitions/market.MatchMarket"
                },
                "match_id": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/result.MatchResult"
                },
                "totalamount": {
                    "type": "number"
                }
            }
        },
        "controller.BetCreationSucessResponse": {
            "type": "object",
            "properties": {
                "bet_id": {
                    "type": "string"
                }
            }
        },
        "controller.BetListResponse": {
            "type": "object",
            "properties": {
                "bets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/bet.BetBase"
                    }
                }
            }
        },
        "controller.BetResponseError": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "market.MatchMarket": {
            "type": "object",
            "properties": {
                "allscores": {
                    "$ref": "#/definitions/option.Option"
                },
                "away": {
                    "$ref": "#/definitions/option.Option"
                },
                "draw": {
                    "$ref": "#/definitions/option.Option"
                },
                "home": {
                    "$ref": "#/definitions/option.Option"
                },
                "match_id": {
                    "type": "string"
                }
            }
        },
        "option.Option": {
            "type": "object",
            "properties": {
                "is_selected": {
                    "type": "boolean"
                },
                "odd": {
                    "type": "number"
                }
            }
        },
        "result.MatchResult": {
            "type": "object",
            "properties": {
                "league_id": {
                    "type": "string"
                },
                "match_id": {
                    "type": "string"
                },
                "teamAwayGoals": {
                    "type": "integer"
                },
                "teamHomeGoals": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost: 9000",
	BasePath:         "api/v1",
	Schemes:          []string{},
	Title:            "Bet API",
	Description:      "This is a bet service for DoBet Application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
