basePath: api/v1
definitions:
  bet.BetBase:
    properties:
      bet_id:
        type: string
      bet_owner:
        type: string
      betgroup:
        items:
          $ref: '#/definitions/bet.SingleBetImpl'
        type: array
      is_finished:
        type: boolean
      status:
        type: string
    required:
    - bet_owner
    - betgroup
    type: object
  bet.SingleBetImpl:
    properties:
      is_lose:
        type: boolean
      isprocessed:
        type: boolean
      league_id:
        type: string
      market:
        $ref: '#/definitions/market.MatchMarket'
      match_id:
        type: string
      result:
        $ref: '#/definitions/result.MatchResult'
      totalamount:
        type: number
    required:
    - market
    - match_id
    - totalamount
    type: object
  controller.BetCreationSucessResponse:
    properties:
      bet_id:
        type: string
    type: object
  controller.BetListResponse:
    properties:
      bets:
        items:
          $ref: '#/definitions/bet.BetBase'
        type: array
    type: object
  controller.BetResponseError:
    properties:
      msg:
        type: string
    type: object
  market.MatchMarket:
    properties:
      allscores:
        $ref: '#/definitions/option.Option'
      away:
        $ref: '#/definitions/option.Option'
      draw:
        $ref: '#/definitions/option.Option'
      home:
        $ref: '#/definitions/option.Option'
      match_id:
        type: string
    type: object
  option.Option:
    properties:
      is_selected:
        type: boolean
      odd:
        type: number
    type: object
  result.MatchResult:
    properties:
      league_id:
        type: string
      match_id:
        type: string
      teamAwayGoals:
        type: integer
      teamHomeGoals:
        type: integer
    type: object
host: 'localhost: 9000'
info:
  contact:
    email: dionisiopaulonamuetho@gmail.com
    name: Dionisio Paulo
    url: meusite.com
  description: This is a bet service for DoBet Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Bet API
  version: "1.0"
paths:
  /bet:
    post:
      consumes:
      - application/json
      description: this route allows to place your bet
      produces:
      - application/json
      responses:
        "200":
          description: bet
          schema:
            $ref: '#/definitions/controller.BetCreationSucessResponse'
        "500":
          description: error
          schema:
            $ref: '#/definitions/controller.BetResponseError'
      summary: make a bet bet in the system
  /bets:
    get:
      consumes:
      - application/json
      description: this route allows you to to get bets in the dobet server
      parameters:
      - description: page
        in: query
        name: int
        type: integer
      - description: perpage
        in: query
        name: int
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: bets
          schema:
            $ref: '#/definitions/controller.BetListResponse'
        "500":
          description: error
          schema:
            $ref: '#/definitions/controller.BetResponseError'
      summary: get all bet in the system
  /bets/:id:
    get:
      consumes:
      - application/json
      description: this route allows you to bets in the dobet server by id
      parameters:
      - description: page
        in: query
        name: int
        type: integer
      - description: perpage
        in: query
        name: int
        type: integer
      - description: id
        in: query
        name: string
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: bets
          schema:
            $ref: '#/definitions/controller.BetListResponse'
        "500":
          description: error
          schema:
            $ref: '#/definitions/controller.BetResponseError'
      summary: get the bets by user id in the system
swagger: "2.0"
