name: payment-build

on:
  push:
    branches: [ master ]
    paths:
      - paymentService/**
      - .github/workflows/payment.yaml
  pull_request:
    branches: [ master ]
    paths:
      - paymentService/**  
      - .github/workflows/payment.yaml
jobs:
  # test:
  #   name: test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Set up Go
  #     uses: actions/setup-go@v3
  #     with:
  #       go-version: 1.18

  #   - name: Test
  #     run: go test -v ./...

  build-and-publish:
    name: build and publish
    # #needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: paymentService
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: namuetho/dobet-payment
          tags: latest
          registry: docker.io
          directory: paymentService
          dockerfile: paymentService/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

